// Global search index — update when adding new Q&A or sections
window.SEARCH_INDEX = [
  // ── JUC ──
  { page: 'juc.html', label: 'JUC', id: 'juc-section',    title: '并发编程核心知识', ctx: 'Java 内存模型、synchronized、volatile、CAS、AQS、线程池、并发容器' },
  { page: 'juc.html', label: 'JUC', id: 'juc-jmm',        title: 'Java 内存模型（JMM）', ctx: 'JMM 定义多线程变量读写规则，解决可见性、有序性和原子性' },
  { page: 'juc.html', label: 'JUC', id: 'juc-sync',       title: 'synchronized 原理', ctx: 'Mark Word、偏向锁→轻量级锁→重量级锁升级、Monitor 机制' },
  { page: 'juc.html', label: 'JUC', id: 'juc-volatile',   title: 'volatile 原理', ctx: '内存屏障、lock 前缀指令、MESI 缓存一致性、可见性和有序性' },
  { page: 'juc.html', label: 'JUC', id: 'juc-cas',        title: 'CAS 与原子类', ctx: 'Compare-And-Swap、ABA 问题、AtomicStampedReference、LongAdder' },
  { page: 'juc.html', label: 'JUC', id: 'juc-aqs',        title: 'AQS 原理', ctx: 'AbstractQueuedSynchronizer、CLH 队列、state 变量、LockSupport' },
  { page: 'juc.html', label: 'JUC', id: 'juc-locks',      title: '常用锁', ctx: 'ReentrantLock、ReentrantReadWriteLock、StampedLock、公平锁' },
  { page: 'juc.html', label: 'JUC', id: 'juc-threadpool', title: '线程池', ctx: 'ThreadPoolExecutor 七参数、核心线程、最大线程、工作队列、拒绝策略' },
  { page: 'juc.html', label: 'JUC', id: 'juc-collections',title: '并发容器', ctx: 'ConcurrentHashMap、CopyOnWriteArrayList、BlockingQueue' },
  { page: 'juc.html', label: 'JUC', id: 'juc-vthread',    title: '虚拟线程（JDK 21）', ctx: 'Virtual Thread、Carrier Thread、Pinning 问题、Scoped Values' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-1',  title: 'volatile 的作用是什么？底层原理是什么？', ctx: 'Q&A' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-2',  title: 'synchronized 的锁升级过程是什么？', ctx: 'Q&A' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-3',  title: 'synchronized 和 ReentrantLock 有什么区别？', ctx: 'Q&A' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-4',  title: 'CAS 是什么？有什么缺点？如何解决 ABA 问题？', ctx: 'Q&A' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-5',  title: 'AQS 的原理是什么？哪些类基于 AQS 实现？', ctx: 'Q&A' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-6',  title: 'ThreadPoolExecutor 有哪些核心参数？各自的作用是什么？', ctx: 'Q&A' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-7',  title: '线程池的拒绝策略有哪些？分别适用什么场景？', ctx: 'Q&A' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-8',  title: '如何合理设置线程池大小？CPU 密集型和 IO 密集型有何不同？', ctx: 'Q&A' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-9',  title: 'ConcurrentHashMap 的实现原理是什么？为什么不允许 null key？', ctx: 'Q&A' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-10', title: 'Java 内存模型（JMM）是什么？happens-before 规则有哪些？', ctx: 'Q&A' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-11', title: 'CountDownLatch、CyclicBarrier、Semaphore 分别适用什么场景？', ctx: 'Q&A' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-12', title: 'ThreadLocal 的原理是什么？如何避免内存泄漏？', ctx: 'Q&A' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-13', title: '什么是死锁？产生的四个必要条件是什么？如何预防和检测？', ctx: 'Q&A' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-14', title: 'ReentrantReadWriteLock 的适用场景和注意事项？', ctx: 'Q&A' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-15', title: 'CompletableFuture 相比 Future 有哪些改进？', ctx: 'Q&A' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-16', title: 'JDK 21 虚拟线程是什么？和平台线程有什么区别？有哪些使用陷阱？', ctx: 'Q&A' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-17', title: '线上 CPU 100%，怎么定位到具体线程和代码行？', ctx: 'Q&A' },
  { page: 'juc.html', label: 'JUC', id: 'q-juc-18', title: '线程池任务堆积了怎么处理？', ctx: 'Q&A' },

  // ── Spring ──
  { page: 'spring.html', label: 'Spring', id: 'spring-ioc',          title: 'IoC & Bean 容器', ctx: 'IoC、BeanFactory、ApplicationContext、BeanDefinition、依赖注入' },
  { page: 'spring.html', label: 'Spring', id: 'spring-lifecycle',     title: 'Bean 生命周期', ctx: '实例化→属性填充→Aware→BeanPostProcessor→初始化→就绪→销毁' },
  { page: 'spring.html', label: 'Spring', id: 'spring-aop',           title: 'AOP 原理', ctx: 'JDK 动态代理、CGLIB 代理、切点表达式、通知类型' },
  { page: 'spring.html', label: 'Spring', id: 'spring-tx',            title: '事务管理', ctx: '@Transactional、传播行为、隔离级别、事务失效场景' },
  { page: 'spring.html', label: 'Spring', id: 'spring-circular',      title: '循环依赖与三级缓存', ctx: '三级缓存、ObjectFactory、早期引用、构造器注入无法解决' },
  { page: 'spring.html', label: 'Spring', id: 'interview-spring-ioc', title: 'Spring IoC 面试题', ctx: '容器原理、Bean 生命周期、作用域、依赖注入高频考点' },
  { page: 'spring.html', label: 'Spring', id: 'interview-spring-aop', title: 'Spring AOP 面试题', ctx: '代理机制、切点表达式、通知类型、AOP 失效场景' },
  { page: 'spring.html', label: 'Spring', id: 'interview-spring-tx',  title: 'Spring 事务面试题', ctx: '传播行为、隔离级别、@Transactional 失效、循环依赖' },
  { page: 'spring.html', label: 'Spring', id: 'q-sp-ioc-1', title: 'Spring IoC 容器的实现原理是什么？BeanFactory 和 ApplicationContext 有什么区别？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-sp-ioc-2', title: '请描述 Spring Bean 完整的生命周期，并说明哪个阶段创建了 AOP 代理？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-sp-ioc-3', title: '@Autowired 和 @Resource 有什么区别？注入时发现多个匹配 Bean 怎么处理？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-sp-ioc-4', title: 'singleton Bean 注入 prototype Bean 时为什么只有一个实例？如何获取每次不同的实例？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-sp-ioc-5', title: 'Spring Boot 自动配置（Auto-Configuration）的原理是什么？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-sp-ioc-6', title: '@Configuration 的 Full 模式和 Lite 模式有什么区别？BeanFactoryPostProcessor 和 BeanPostProcessor 有什么区别？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-sp-aop-1', title: 'JDK 动态代理和 CGLIB 代理的实现原理有何不同？Spring 如何选择？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-sp-aop-2', title: 'AOP 失效的常见原因有哪些？如何排查"同类调用 @Transactional 不生效"？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-sp-aop-3', title: '@Around、@Before、@After、@AfterReturning、@AfterThrowing 的执行顺序？多个切面如何排序？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-sp-aop-4', title: 'Spring AOP 和 AspectJ 有什么区别？各自适用什么场景？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-sp-aop-5', title: '@Async 的实现原理是什么？有哪些常见失效场景？异常如何捕获？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-sp-tx-1',  title: 'REQUIRED 和 REQUIRES_NEW 的区别？NESTED 和 REQUIRES_NEW 的区别？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-sp-tx-2',  title: '@Transactional 有哪些常见失效场景？分别如何解决？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-sp-tx-3',  title: 'Spring 事务的隔离级别有哪些？DEFAULT 对应的是什么？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-sp-tx-4',  title: 'Spring 三级缓存为什么能解决循环依赖？为什么构造器注入无法解决？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-sp-tx-5',  title: '@Transactional 的 readOnly=true 有什么作用？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-sp-tx-6',  title: '微服务中 @Transactional 无法解决跨服务事务，常见的分布式事务方案有哪些？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-spring-18', title: '@Transactional 不生效，你遇到过哪些坑？怎么排查？', ctx: 'Q&A' },
  { page: 'spring.html', label: 'Spring', id: 'q-spring-19', title: '线上应用启动报循环依赖，怎么解决？', ctx: 'Q&A' },

  // ── GC ──
  { page: 'gc-principles.html', label: 'GC', id: 'g1-section',     title: 'G1 GC 核心设计', ctx: 'Region 分区、SATB 并发标记、RSet、CSet、Evacuation 疏散回收' },
  { page: 'gc-principles.html', label: 'GC', id: 'g1-heap',        title: 'G1 堆分区模型', ctx: 'Region 大小、Eden/Survivor/Old/Humongous Region、动态调整 Young 区' },
  { page: 'gc-principles.html', label: 'GC', id: 'g1-satb',        title: 'SATB 并发标记', ctx: 'Snapshot-At-The-Beginning、写前屏障、SATB 队列、浮动垃圾' },
  { page: 'gc-principles.html', label: 'GC', id: 'g1-rset',        title: 'Remembered Set (RSet)', ctx: '跨 Region 引用追踪、写后屏障、Dirty Card Queue、Refinement 线程' },
  { page: 'gc-principles.html', label: 'GC', id: 'g1-cset',        title: 'Collection Set (CSet)', ctx: '垃圾优先、停顿时间预算、MaxGCPauseMillis 200ms 默认' },
  { page: 'gc-principles.html', label: 'GC', id: 'g1-evacuation',  title: 'Evacuation 疏散回收', ctx: 'STW 并行复制、存活对象迁移、Region 整块释放、to-space exhausted' },
  { page: 'gc-principles.html', label: 'GC', id: 'g1-young',       title: 'Young GC 流程', ctx: 'GCLAB、并行疏散、Eden 清空、Survivor 晋升、Evacuation Failure' },
  { page: 'gc-principles.html', label: 'GC', id: 'g1-flow',        title: 'G1 完整 GC 流程', ctx: 'Young GC→并发标记→Mixed GC→Full GC 退化、IHOP 阈值 45%' },
  { page: 'gc-principles.html', label: 'GC', id: 'zgc-section',    title: 'ZGC 核心设计', ctx: '染色指针、多重虚拟内存映射、读屏障、亚毫秒停顿' },
  { page: 'gc-principles.html', label: 'GC', id: 'zgc-pointer',    title: '染色指针', ctx: '64 位指针高位编码 GC 元数据、Marked0/Marked1/Remapped/Finalizable' },
  { page: 'gc-principles.html', label: 'GC', id: 'zgc-multimap',   title: '多重虚拟内存映射', ctx: 'mmap 同一物理内存映射三个虚拟地址空间，配合染色指针访问' },
  { page: 'gc-principles.html', label: 'GC', id: 'zgc-barrier',    title: '读屏障（Load Barrier）', ctx: '每次堆引用加载时检查 Remapped 位，按需修复旧指针' },
  { page: 'gc-principles.html', label: 'GC', id: 'zgc-cycle',      title: 'ZGC 并发 GC 周期', ctx: '三次 STW（均 <1ms）、并发标记、并发重定位、延迟修复策略' },
  { page: 'gc-principles.html', label: 'GC', id: 'interview-g1',   title: 'G1 面试题', ctx: '堆分区、SATB、RSet、CSet、Evacuation Failure 核心考点' },
  { page: 'gc-principles.html', label: 'GC', id: 'interview-zgc',  title: 'ZGC 面试题', ctx: '染色指针、多重映射、读屏障、GC 周期 STW 次数' },
  { page: 'gc-principles.html', label: 'GC', id: 'interview-cms',  title: 'CMS 面试题', ctx: '六阶段流程、CMF、内存碎片、增量更新' },
  { page: 'gc-principles.html', label: 'GC', id: 'interview-cmp',  title: 'G1 vs ZGC 对比面试题', ctx: '停顿模型差异、吞吐量、RSet vs 全堆标记、选型依据' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-g1-1',  title: 'G1 的堆分区模型与传统分代堆有什么本质区别？Humongous Region 的分配阈值是多少？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-g1-2',  title: '请解释 SATB 算法的核心思想，以及"写前屏障"在其中的作用。SATB 会引入什么副作用？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-g1-3',  title: 'G1 的 Remembered Set（RSet）存储的是什么方向的引用？维护 RSet 的机制是什么？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-g1-4',  title: 'G1 为什么叫"Garbage First"？CSet 是如何选取的？默认停顿时间目标是多少？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-g1-5',  title: 'Evacuation 阶段是 STW 还是并发执行？如果 to-space 耗尽会发生什么？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-g1-6',  title: 'G1 有哪三种 GC 模式？各自的触发条件和回收范围是什么？Mixed GC 如何逐步清理老年代？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-g1-7',  title: 'TAMS 指针是什么？G1 如何保证并发标记期间新分配的对象不被误回收？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-g1-8',  title: 'Young GC 的并行疏散是如何运作的？GCLAB 的作用是什么？什么情况下触发 Evacuation Failure？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-zgc-1', title: 'ZGC 染色指针的核心思想是什么？各元数据位的含义是什么？为什么只能在 64 位 JVM 上使用？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-zgc-2', title: 'ZGC 为什么需要多重虚拟内存映射？对物理内存消耗有影响吗？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-zgc-3', title: 'ZGC 读屏障的工作原理是什么？它如何保证并发重定位的正确性？与 G1 写后屏障开销有什么不同？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-zgc-4', title: 'ZGC 一次完整 GC 周期有几次 STW？为什么 ZGC 的停顿时间基本不随堆大小增长？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-zgc-5', title: 'ZGC 并发重定位阶段，旧指针是何时被批量修复的？GC 结束时仍有旧指针未修复会怎样？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-zgc-6', title: 'Generational ZGC（JDK 21）相比传统 ZGC 解决了什么问题？核心设计变化是什么？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-cms-1', title: 'CMS 的六个 GC 阶段是什么？哪些是 STW？为什么 Remark 比 G1 停顿更长？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-cms-2', title: '什么是 Concurrent Mode Failure？触发条件是什么？如何预防？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-cms-3', title: 'CMS 为什么会产生内存碎片？碎片化如何影响性能？有什么解决手段？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-cms-4', title: 'CMS 使用增量更新而非 SATB，各有什么代价？G1 为什么选择 SATB？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-cms-5', title: 'CMS 在 JDK 14 被移除前，为什么还有人选它而不是 G1？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-cmp-1', title: 'G1 和 ZGC 的停顿时间模型有何根本差异？为什么 G1 的停顿随堆变大而增长？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-cmp-2', title: 'ZGC 的吞吐量为什么通常低于 G1？ZGC 有哪些机制可以弥补这一差距？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-cmp-3', title: 'G1 和 ZGC 在"跨区引用追踪"上的机制分别是什么？ZGC 为何可以不用 RSet？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-cmp-4', title: 'G1 和 ZGC 各自的"灾难场景"是什么？如何诊断和规避？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-cmp-5', title: '在实际项目中如何选择 G1 还是 ZGC？请给出决策依据和典型场景。', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-cmp-6', title: '生产环境如何诊断 G1 / ZGC 的 GC 性能问题？两者的调优思路有何不同？', ctx: 'Q&A' },
  { page: 'gc-principles.html', label: 'GC', id: 'q-gc-p1', title: '线上频繁 Full GC 怎么排查？', ctx: 'Q&A' },

  // ── MySQL ──
  { page: 'mysql.html', label: 'MySQL', id: 'mysql-section',      title: 'MySQL 核心知识', ctx: 'B+ Tree 索引、MVCC、Next-Key Lock、日志体系、两阶段提交、主从复制' },
  { page: 'mysql.html', label: 'MySQL', id: 'mysql-architecture', title: '核心架构', ctx: '连接器→解析器→优化器→执行器→InnoDB 存储引擎、Buffer Pool' },
  { page: 'mysql.html', label: 'MySQL', id: 'mysql-engine',       title: '存储引擎', ctx: 'InnoDB vs MyISAM、聚簇索引、ACID 支持、Change Buffer' },
  { page: 'mysql.html', label: 'MySQL', id: 'mysql-index',        title: 'B+ Tree 索引原理', ctx: '聚簇索引、二级索引、最左匹配、覆盖索引、回表、索引下推' },
  { page: 'mysql.html', label: 'MySQL', id: 'mysql-transaction',  title: '事务与 ACID', ctx: '原子性、一致性、隔离性、持久性、四种隔离级别' },
  { page: 'mysql.html', label: 'MySQL', id: 'mysql-mvcc',         title: 'MVCC 多版本并发', ctx: 'ReadView、undo log 版本链、RC 每次重建、RR 首次后复用' },
  { page: 'mysql.html', label: 'MySQL', id: 'mysql-lock',         title: '锁机制', ctx: '行锁、间隙锁 Gap Lock、Next-Key Lock、意向锁、死锁检测' },
  { page: 'mysql.html', label: 'MySQL', id: 'mysql-log',          title: '日志体系', ctx: 'redo log（WAL）、binlog、undo log、两阶段提交、crash recovery' },
  { page: 'mysql.html', label: 'MySQL', id: 'mysql-optimize',     title: '查询优化', ctx: 'EXPLAIN、慢查询日志、覆盖索引、分页优化、统计信息' },
  { page: 'mysql.html', label: 'MySQL', id: 'mysql-replication',  title: '主从复制', ctx: 'binlog 同步、IO 线程/SQL 线程、半同步、并行复制、主从延迟' },
  { page: 'mysql.html', label: 'MySQL', id: 'mysql-sharding',     title: '分库分表', ctx: 'ShardingSphere JDBC/Proxy 模式、哈希/范围分片、跨分片 JOIN、ES 二级索引、在线迁移 Canal CDC' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-1',  title: '一条 SELECT 语句的完整执行流程是什么？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-2',  title: 'count(*)、count(1)、count(id) 哪个更快？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-3',  title: '什么是幻读？InnoDB 如何解决？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-4',  title: 'redo log 和 binlog 的区别？为什么需要两阶段提交？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-5',  title: 'int(10) 和 int(11) 有区别吗？VARCHAR(100) 和 VARCHAR(10) 性能一样吗？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-6',  title: '为什么不建议用 UUID 作主键？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-7',  title: '优化器什么时候会放弃索引选择全表扫描？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-8',  title: '联合索引的最左匹配原则是什么？哪些情况会导致索引失效？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-9',  title: '什么是覆盖索引？为什么能避免回表，性能提升有多大？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-10', title: 'MVCC 的实现原理是什么？ReadView 什么时候创建？RC 和 RR 的区别体现在哪？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-11', title: 'MySQL 死锁是如何产生的？InnoDB 如何检测死锁？出现死锁如何排查和预防？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-12', title: '如何排查慢查询？EXPLAIN 输出中哪些字段最重要？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-13', title: '大表（千万行级）如何安全地加字段或加索引？Online DDL 的原理是什么？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-14', title: '主从复制延迟的常见原因有哪些？如何监控和缓解？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-15', title: 'InnoDB 的 change buffer 是什么？什么场景有效，什么场景无效？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-16', title: '线上出现死锁，你的排查思路是什么？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-17', title: '一条慢 SQL 告警了，怎么定位和优化？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-18', title: '主从延迟严重，业务读到了旧数据，怎么处理？', ctx: 'Q&A' },
  { page: 'mysql.html', label: 'MySQL', id: 'q-mysql-19', title: '分库分表后如何不停机迁移存量数据？有哪些关键风险点？', ctx: 'Q&A' },

  // ── Redis ──
  { page: 'redis.html', label: 'Redis', id: 'redis-section',     title: 'Redis 核心知识', ctx: '数据类型、持久化、内存淘汰、缓存穿透/击穿/雪崩、哨兵 Cluster、分布式锁' },
  { page: 'redis.html', label: 'Redis', id: 'redis-datatype',    title: '数据结构与底层编码', ctx: 'String/List/Hash/Set/ZSet 底层 listpack、跳表、哈希表' },
  { page: 'redis.html', label: 'Redis', id: 'redis-persistence', title: 'RDB / AOF 持久化', ctx: 'RDB 快照、AOF 追加写、混合持久化 aof-use-rdb-preamble' },
  { page: 'redis.html', label: 'Redis', id: 'redis-eviction',    title: '内存淘汰策略', ctx: 'noeviction、allkeys-lru、volatile-lru、allkeys-lfu、TTL 淘汰' },
  { page: 'redis.html', label: 'Redis', id: 'redis-cache',       title: '缓存穿透 / 击穿 / 雪崩', ctx: '布隆过滤器、空值缓存、互斥锁、逻辑过期、随机 TTL' },
  { page: 'redis.html', label: 'Redis', id: 'redis-ha',          title: '哨兵 & Cluster 集群', ctx: '主从复制、哨兵自动故障切换、Cluster 哈希槽 16384、ASK/MOVED' },
  { page: 'redis.html', label: 'Redis', id: 'redis-lock',        title: '分布式锁', ctx: 'SET NX EX、Redisson 看门狗续期、Redlock 算法' },
  { page: 'redis.html', label: 'Redis', id: 'redis-commands',    title: '常规指令速查', ctx: 'String/List/Hash/Set/ZSet/Key 全类型命令速查、SCAN 替代 KEYS、UNLINK 异步删除、事务 MULTI/EXEC、Lua EVAL' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-1',  title: 'Redis 为什么这么快？', ctx: 'Q&A' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-2',  title: 'Redis 单线程为什么还那么快？瓶颈在哪里？', ctx: 'Q&A' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-3',  title: 'RDB 和 AOF 如何选择？', ctx: 'Q&A' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-4',  title: '如何保证缓存与数据库的数据一致性？', ctx: 'Q&A' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-5',  title: 'Redis Cluster 如何扩容？slot 迁移过程是什么？', ctx: 'Q&A' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-6',  title: '什么情况下 Redis 会阻塞？如何避免？', ctx: 'Q&A' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-7',  title: 'Big Key 问题如何排查和处理？', ctx: 'Q&A' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-8',  title: '热点 Key 问题如何解决？', ctx: 'Q&A' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-9',  title: 'Redis 事务与 Lua 脚本的区别？', ctx: 'Q&A' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-10', title: '如何用 Redis 实现限流？', ctx: 'Q&A' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-11', title: '缓存穿透、击穿、雪崩如何区分？各自如何解决？', ctx: 'Q&A' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-12', title: 'Redis 分布式锁如何实现？Redlock 解决了什么问题？', ctx: 'Q&A' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-13', title: 'Redis 主从复制原理是什么？哨兵如何实现自动故障切换？', ctx: 'Q&A' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-14', title: 'Redis 的内存淘汰策略有哪些？如何选择？', ctx: 'Q&A' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-15', title: 'Redis Sentinel 与 Cluster 如何选型？', ctx: 'Q&A' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-16', title: '线上 Redis 内存暴涨怎么排查？', ctx: 'Q&A' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-17', title: '缓存和数据库双写一致性怎么保证？', ctx: 'Q&A' },
  { page: 'redis.html', label: 'Redis', id: 'q-redis-18', title: 'Redis Cluster 某节点挂了，故障转移全过程是什么？', ctx: 'Q&A' },

  // ── MQ ──
  { page: 'mq.html', label: 'MQ', id: 'mq-section',     title: '消息队列核心知识', ctx: 'Kafka 高性能、RocketMQ 事务消息、可靠性三段保障、顺序性、幂等消费' },
  { page: 'mq.html', label: 'MQ', id: 'mq-why',         title: '为什么用 MQ', ctx: '服务解耦、异步处理、流量削峰、引入代价：可用性降低' },
  { page: 'mq.html', label: 'MQ', id: 'mq-compare',     title: '主流 MQ 横向对比', ctx: 'Kafka 高吞吐、RocketMQ 金融级、RabbitMQ 功能丰富' },
  { page: 'mq.html', label: 'MQ', id: 'mq-kafka',       title: 'Kafka 核心原理', ctx: '顺序写、零拷贝、批量压缩、分区并行、ISR/HW/LEO、副本机制' },
  { page: 'mq.html', label: 'MQ', id: 'mq-rocketmq',    title: 'RocketMQ 核心原理', ctx: 'CommitLog 顺序写、ConsumeQueue 索引、事务消息两阶段提交' },
  { page: 'mq.html', label: 'MQ', id: 'mq-reliability', title: '消息可靠性三段保障', ctx: '生产者确认 acks、Broker 持久化、消费者手动 ack' },
  { page: 'mq.html', label: 'MQ', id: 'mq-order',       title: '消息顺序性', ctx: '单 Partition 内有序、业务 key 路由固定分区' },
  { page: 'mq.html', label: 'MQ', id: 'mq-idempotent',  title: '消息幂等解决重复消费', ctx: 'at-least-once 语义、数据库唯一索引、Redis SETNX 去重' },
  { page: 'mq.html', label: 'MQ', id: 'mq-advanced',    title: '死信队列 & 延迟消息', ctx: 'DLQ 死信队列、RocketMQ 延迟级别、Kafka 时间轮' },
  { page: 'mq.html', label: 'MQ', id: 'q-mq-1',  title: '为什么使用 MQ？引入 MQ 有哪些缺点需要应对？', ctx: 'Q&A' },
  { page: 'mq.html', label: 'MQ', id: 'q-mq-2',  title: 'Kafka 为什么吞吐量能达到百万级？', ctx: 'Q&A' },
  { page: 'mq.html', label: 'MQ', id: 'q-mq-3',  title: 'Kafka 如何保证消息不丢失（三段分析）？', ctx: 'Q&A' },
  { page: 'mq.html', label: 'MQ', id: 'q-mq-4',  title: '如何保证消息的顺序性？', ctx: 'Q&A' },
  { page: 'mq.html', label: 'MQ', id: 'q-mq-5',  title: '如何解决消息重复消费（幂等）？', ctx: 'Q&A' },
  { page: 'mq.html', label: 'MQ', id: 'q-mq-6',  title: '消息积压了怎么处理？', ctx: 'Q&A' },
  { page: 'mq.html', label: 'MQ', id: 'q-mq-7',  title: 'Kafka 的 ISR 是什么？HW 和 LEO 的区别？', ctx: 'Q&A' },
  { page: 'mq.html', label: 'MQ', id: 'q-mq-8',  title: 'Kafka 的 acks 参数如何选择？', ctx: 'Q&A' },
  { page: 'mq.html', label: 'MQ', id: 'q-mq-9',  title: 'Kafka Consumer Group 是什么？Rebalance 何时触发？', ctx: 'Q&A' },
  { page: 'mq.html', label: 'MQ', id: 'q-mq-10', title: 'RocketMQ 事务消息的原理是什么？', ctx: 'Q&A' },
  { page: 'mq.html', label: 'MQ', id: 'q-mq-11', title: '死信队列是什么？如何处理死信消息？', ctx: 'Q&A' },
  { page: 'mq.html', label: 'MQ', id: 'q-mq-12', title: '延迟消息如何实现？RocketMQ 和 Kafka 有什么区别？', ctx: 'Q&A' },
  { page: 'mq.html', label: 'MQ', id: 'q-mq-13', title: 'Kafka 和 RocketMQ 存储架构的核心区别？', ctx: 'Q&A' },
  { page: 'mq.html', label: 'MQ', id: 'q-mq-14', title: '如何设计一个可靠的消息投递系统（本地消息表方案）？', ctx: 'Q&A' },
  { page: 'mq.html', label: 'MQ', id: 'q-mq-15', title: 'Kafka 的零拷贝（Zero-Copy）是如何实现的？', ctx: 'Q&A' },
  { page: 'mq.html', label: 'MQ', id: 'q-mq-p1', title: '实战：消息积压了几百万条，怎么紧急处理？', ctx: 'Q&A' },
  { page: 'mq.html', label: 'MQ', id: 'q-mq-p2', title: '实战：消费者处理消息时抛异常了，消息会丢吗？怎么处理？', ctx: 'Q&A' },

  // ── 分布式 ──
  { page: 'distributed.html', label: '分布式', id: 'dist-section',    title: '分布式系统核心知识', ctx: 'CAP/BASE 理论、分布式事务、分布式锁、注册中心、Snowflake、限流熔断' },
  { page: 'distributed.html', label: '分布式', id: 'dist-cap',        title: 'CAP & BASE 理论', ctx: 'CAP 三选二、一致性/可用性/分区容忍性、BASE 最终一致性' },
  { page: 'distributed.html', label: '分布式', id: 'dist-transaction', title: '分布式事务', ctx: '2PC、TCC（Try-Confirm-Cancel）、Saga、本地消息表、Seata AT' },
  { page: 'distributed.html', label: '分布式', id: 'dist-lock',       title: '分布式锁', ctx: 'Redis SET NX EX、Redisson 看门狗、ZooKeeper 临时顺序节点' },
  { page: 'distributed.html', label: '分布式', id: 'dist-registry',   title: '注册中心与服务发现', ctx: 'Nacos AP/CP 可切换（Distro/Raft）、Eureka AP、ZooKeeper CP、健康检查' },
  { page: 'distributed.html', label: '分布式', id: 'dist-raft',       title: 'Raft 共识算法', ctx: 'Leader 选举（随机超时 + 多数票）、日志复制 AppendEntries、安全性保证、etcd/TiKV/Nacos 使用' },
  { page: 'distributed.html', label: '分布式', id: 'dist-id',         title: '分布式 ID', ctx: 'Snowflake 时间戳+机器ID+序列号、号段模式、Redis incr' },
  { page: 'distributed.html', label: '分布式', id: 'dist-ratelimit',  title: '限流与熔断', ctx: '令牌桶、漏桶、滑动窗口、Hystrix/Sentinel 熔断三态' },
  { page: 'distributed.html', label: '分布式', id: 'dist-consistent', title: '一致性哈希', ctx: '哈希环、虚拟节点、节点变动只影响相邻数据' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-1',  title: 'CAP 理论是什么？分布式系统为什么不能同时满足三者？', ctx: 'Q&A' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-2',  title: 'BASE 理论是什么？和 ACID 有什么区别？', ctx: 'Q&A' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-3',  title: '分布式事务有哪些解决方案？各自适用什么场景？', ctx: 'Q&A' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-4',  title: '2PC 的原理是什么？有哪些缺陷？', ctx: 'Q&A' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-5',  title: 'TCC 的原理是什么？和 2PC 相比有什么优缺点？', ctx: 'Q&A' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-6',  title: '如何用 Redis 实现分布式锁？有哪些常见问题？', ctx: 'Q&A' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-7',  title: 'Redisson 的看门狗机制是什么？如何防止锁提前过期？', ctx: 'Q&A' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-8',  title: 'ZooKeeper 如何实现分布式锁？和 Redis 分布式锁有什么区别？', ctx: 'Q&A' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-9',  title: 'Nacos、Eureka、ZooKeeper 作为注册中心有什么区别？如何选型？', ctx: 'Q&A' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-10', title: 'Snowflake 算法的原理是什么？有哪些缺陷？', ctx: 'Q&A' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-11', title: '如何实现接口限流？令牌桶和漏桶算法有什么区别？', ctx: 'Q&A' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-12', title: '什么是服务熔断？熔断器的三种状态是什么？', ctx: 'Q&A' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-13', title: '一致性哈希算法是什么？如何解决数据倾斜问题？', ctx: 'Q&A' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-14', title: '分布式系统中如何保证接口幂等性？', ctx: 'Q&A' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-15', title: '什么是分布式链路追踪？TraceId 如何实现全链路透传？', ctx: 'Q&A' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-16', title: 'Raft 算法的 Leader 选举和日志复制流程是什么？和 Paxos 有什么区别？', ctx: 'Q&A' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-p1', title: 'Redisson 分布式锁续期失败导致业务异常，怎么排查？', ctx: 'Q&A' },
  { page: 'distributed.html', label: '分布式', id: 'q-dist-p2', title: 'Seata AT 模式全局事务回滚失败怎么处理？', ctx: 'Q&A' },

  // ── JVM ──
  { page: 'jvm.html', label: 'JVM', id: 'jvm-section',    title: 'JVM 内存与类加载', ctx: '运行时数据区、对象内存布局、Class 文件、类加载、双亲委派、JIT' },
  { page: 'jvm.html', label: 'JVM', id: 'jvm-runtime',    title: '运行时数据区', ctx: '线程私有：虚拟机栈/本地方法栈/PC；线程共享：堆/方法区（Metaspace）' },
  { page: 'jvm.html', label: 'JVM', id: 'jvm-obj',        title: '对象内存布局', ctx: '对象头（Mark Word + 类指针）、实例数据、对齐填充、压缩指针 Oops' },
  { page: 'jvm.html', label: 'JVM', id: 'jvm-classfile',  title: 'Class 文件结构', ctx: '魔数、常量池、字段/方法描述符、属性表、字节码指令' },
  { page: 'jvm.html', label: 'JVM', id: 'jvm-classload',  title: '类加载机制', ctx: '加载→验证→准备→解析→初始化→使用→卸载、<clinit>' },
  { page: 'jvm.html', label: 'JVM', id: 'jvm-delegation', title: '双亲委派模型', ctx: 'Bootstrap→Extension→Application、打破：SPI、热部署、OSGi' },
  { page: 'jvm.html', label: 'JVM', id: 'jvm-jit',        title: 'JIT 编译与调优', ctx: '解释执行 vs JIT、C1/C2 分层编译、逃逸分析、方法内联、OSR' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-1',  title: 'JVM 运行时数据区有哪些部分？各自的作用和线程归属？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-2',  title: '堆和栈的区别是什么？为什么局部变量比对象快？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-3',  title: 'Java 对象的内存布局是怎样的？对象头包含什么信息？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-4',  title: '什么是压缩指针（Compressed Oops）？为什么能节省内存？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-5',  title: '类加载的完整过程是什么？每个阶段做什么？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-6',  title: '什么情况下会触发类的初始化？什么情况不会？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-7',  title: '双亲委派模型是什么？为什么要打破它？有哪些打破的场景？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-8',  title: 'PermGen 和 Metaspace 有什么区别？为什么 JDK 8 要改？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-9',  title: 'JIT 编译的分层编译是怎么回事？C1 和 C2 有什么区别？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-10', title: '什么是逃逸分析？能带来哪些优化？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-11', title: 'JVM 中对象的创建过程是什么？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-12', title: '什么是 StackOverflowError 和 OOM？分别在什么情况下发生？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-13', title: 'Class.forName() 和 ClassLoader.loadClass() 有什么区别？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-14', title: '什么是强引用、软引用、弱引用、虚引用？各自的使用场景？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-15', title: '线上服务应该配置哪些 JVM 参数？为什么 -Xms 和 -Xmx 要设成一样？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-p1', title: '线上堆 OOM 了，jstat / jmap / MAT 排查全流程是什么？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-p2', title: 'Metaspace OOM 怎么定位？是什么原因导致的？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-p3', title: '容器（K8s / Docker）环境下 JVM 内存参数应该怎么设置？', ctx: 'Q&A' },
  { page: 'jvm.html', label: 'JVM', id: 'q-jvm-p4', title: '服务 GC 停顿突然变长，怎么系统排查？', ctx: 'Q&A' },

  // ── 架构 ──
  { page: 'architecture.html', label: '架构', id: 'arch-section', title: '微服务架构与 DDD 领域建模', ctx: '微服务、DDD、服务拆分、分布式事务、服务容错、可观测性' },
  { page: 'architecture.html', label: '架构', id: 'arch-ms',  title: '微服务架构', ctx: '微服务与单体区别、服务拆分、同步/异步通信、注册发现、配置中心、API 网关、分布式事务、服务容错、可观测性、灰度治理' },
  { page: 'architecture.html', label: '架构', id: 'arch-ddd', title: 'DDD 与领域建模', ctx: '限界上下文、统一语言、防腐层 ACL、实体/值对象/聚合根、贫血/充血模型、领域事件、CQRS、Event Sourcing、四层架构' },
  { page: 'architecture.html', label: '架构', id: 'arch-qa',  title: '架构面试题（实战）', ctx: '微服务 / DDD 实战场景题' },
  { page: 'architecture.html', label: '架构', id: 'q-arch-p1', title: '用 DDD 建模「订单子域」：从限界上下文到四层代码', ctx: 'Q&A' },
  { page: 'architecture.html', label: '架构', id: 'q-arch-p2', title: '设计一个高可用订单微服务（拆分/通信/事务/容错/灰度）', ctx: 'Q&A' },
  { page: 'architecture.html', label: '架构', id: 'q-arch-1',  title: '把单体电商拆成微服务，怎么拆？拆哪些、不拆哪些、粒度怎么控？', ctx: 'Q&A' },
  { page: 'architecture.html', label: '架构', id: 'q-arch-2',  title: '一次下单要「创建订单+扣库存+扣积分」，如何保证数据最终一致？', ctx: 'Q&A' },
  { page: 'architecture.html', label: '架构', id: 'q-arch-3',  title: '服务注册中心选 Nacos 还是 Eureka？区别在哪？', ctx: 'Q&A' },
  { page: 'architecture.html', label: '架构', id: 'q-arch-4',  title: 'API 网关和 Nginx 反向代理有什么区别？网关必须做哪些事？', ctx: 'Q&A' },
  { page: 'architecture.html', label: '架构', id: 'q-arch-5',  title: '微服务雪崩怎么防？超时/重试/熔断/降级/隔离分别怎么配？', ctx: 'Q&A' },
  { page: 'architecture.html', label: '架构', id: 'q-arch-6',  title: '怎么把贫血的 OrderService 改造成充血模型？给代码前后对比。', ctx: 'Q&A' },
  { page: 'architecture.html', label: '架构', id: 'q-arch-7',  title: '聚合根 Order 包含多个 OrderItem，为什么外部不能直接改 OrderItem？', ctx: 'Q&A' },
  { page: 'architecture.html', label: '架构', id: 'q-arch-8',  title: '领域事件 OrderPaidEvent 发布后，如何保证不丢失、不重复？', ctx: 'Q&A' },
  { page: 'architecture.html', label: '架构', id: 'q-arch-9',  title: 'CQRS 适用什么场景？订单「我的订单列表」和「下单」如何拆分？', ctx: 'Q&A' },
  { page: 'architecture.html', label: '架构', id: 'q-arch-10', title: '如何用 DDD 四层架构组织一个 Spring Boot 项目的目录？', ctx: 'Q&A' },
  { page: 'architecture.html', label: '架构', id: 'q-arch-11', title: '如何实现金丝雀/灰度发布？结合网关+注册中心标签路由如何按比例切流？', ctx: 'Q&A' },
  { page: 'architecture.html', label: '架构', id: 'q-arch-12', title: '微服务配置中心（Nacos/Apollo）解决了什么？配置热更新原理？', ctx: 'Q&A' },
  { page: 'architecture.html', label: '架构', id: 'q-arch-13', title: 'TraceID 怎么在跨服务调用中传递？SkyWalking 如何无侵入接入？', ctx: 'Q&A' },
  { page: 'architecture.html', label: '架构', id: 'q-arch-14', title: '两个服务都要用「用户」概念（账号 vs 画像），如何用防腐层 ACL 避免耦合？', ctx: 'Q&A' },
];
